//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartInventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        public string NoOf { get; set; }
        public string Equipment1 { get; set; }
        public int ID { get; set; }
        public string RoomNumber { get; set; }
        public string Model { get; set; }
        public string PurchaseDate { get; set; }
        public string UNBCCode { get; set; }
        public string SerialNo { get; set; }
        public string PO { get; set; }
        public string PurchasePrice { get; set; }
        public string TotalPrice { get; set; }
        public string Vendor { get; set; }
        public string ModelBrandInfo { get; set; }
        public string TypeOfAnalysis { get; set; }
        public string PotentialUse { get; set; }
        public string IsInGoodUse { get; set; }
        public string CurrentUsersOfEquipment { get; set; }
        public string Revenue { get; set; }
        public string OtherUsefulInfo { get; set; }
        public string Contact { get; set; }
        public string BarCode { get; set; }
    }
}
